my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "ur5_tool0"
    robot_base_link: "ur5_base_link"
    target_frame_topic: "target_frame"
    joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

    pd_gains:
        trans_x: {p: 10.0}
        trans_y: {p: 10.0}
        trans_z: {p: 10.0}
        rot_x: {p: 1.0}
        rot_y: {p: 1.0}
        rot_z: {p: 1.0}


my_motion_control_handle:
   type: "cartesian_controllers/MotionControlHandle"
   end_effector_link: "ur5_tool0"
   robot_base_link: "ur5_base_link"
   target_frame_topic: "/my_cartesian_motion_controller/target_frame"
   joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 500