All:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

  joint_weights:
   weights: [.1, 10, 10, 10, 10, 10, 10]
   names: [ axis1_joint,
                  ur5_elbow_joint,
                  ur5_shoulder_lift_joint,
                  ur5_shoulder_pan_joint,
                  ur5_wrist_1_joint,
                  ur5_wrist_2_joint,
                  ur5_wrist_3_joint]


